### ISSUE TITLE
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window'

### ISSUE THREAD

**Issue by thiswallz** [stackblitz/core#1051]
Trying it under google chrome: Version 74.0.3729.108

Not sure if this is bs of a proxy settings, 

Error:
document not ready yet, trying again in 500 milliseconds...
relay-e10048b22f16c66d032db.js:1 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at e.initComms (https://c.staticblitz.com/assets/relay-e10048b22f16c66d032db.js:1:4580)
    at Object.3421 (https://c.staticblitz.com/assets/relay-e10048b22f16c66d032db.js:1:3338)
    at n (https://c.staticblitz.com/assets/relay-e10048b22f16c66d032db.js:1:110)
    at Object.3420 (https://c.staticblitz.com/assets/relay-e10048b22f16c66d032db.js:1:3256)
    at n (https://c.staticblitz.com/assets/relay-e10048b22f16c66d032db.js:1:110)
    at https://c.staticblitz.com/assets/relay-e10048b22f16c66d032db.js:1:484
    at https://c.staticblitz.com/assets/relay-e10048b22f16c66d032db.js:1:496

**Comment by Joseph7695** [comment]
Facing the same problem, it could work if I opened it through the "Open in new window" option though

**Comment by Joseph7695** [comment]
https://github.com/stackblitz/core/issues/162#issuecomment-357656965

This solved it for me

**Comment by purplem1lk** [comment]
Thank you for your patience - This issue has been resolved with the highest rated comment from #162. If your issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
