### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Failed to resolve module specifier 'firebase/auth'

### ISSUE THREAD

**Issue by SiddAjmera** [stackblitz/core#1210]
Getting this error when I'm trying to install @angular/fire on StackBlitz.

### Version info

**Angular:**

9.1.0

**Firebase:**

7.13.2

**AngularFire:**

Tried with both 6.0.0 and 6.0.0-rc.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

I'm using this on StackBlitz.

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

https://stackblitz.com/edit/kittygram-oauth

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

``` ERROR
Error: Uncaught (in promise): TypeError: Failed to resolve module specifier 'firebase/auth'
TypeError: Failed to resolve module specifier 'firebase/auth'
at eval (https://kittygram-oauth.stackblitz.io/turbo_modules/@angular/fire@6.0.0/bundles/angular-fire-auth.umd.js:26:27)
at ZoneDelegate.invoke (https://kittygram-oauth.stackblitz.io/turbo_modules/zone.js@0.10.3/dist/zone.js:386:30)
at Zone.run (https://kittygram-oauth.stackblitz.io/turbo_modules/zone.js@0.10.3/dist/zone.js:143:47)
at NgZone.runOutsideAngular (https://kittygram-oauth.stackblitz.io/turbo_modules/@angular/core@9.1.0/bundles/core.umd.js:27926:32)
at SwitchMapSubscriber.eval [as project] (https://kittygram-oauth.stackblitz.io/turbo_modules/@angular/fire@6.0.0/bundles/angular-fire-auth.umd.js:23:39)
at SwitchMapSubscriber._next (https://kittygram-oauth.stackblitz.io/turbo_modules/rxjs@6.5.5/internal/operators/switchMap.js:49:27)
at SwitchMapSubscriber.Subscriber.next (https://kittygram-oauth.stackblitz.io/turbo_modules/rxjs@6.5.5/internal/Subscriber.js:66:18)
at Notification.observe (https://kittygram-oauth.stackblitz.io/turbo_modules/rxjs@6.5.5/internal/Notification.js:22:50)
at QueueAction.ObserveOnSubscriber.dispatch (https://kittygram-oauth.stackblitz.io/turbo_modules/rxjs@6.5.5/internal/operators/observeOn.js:48:22)
at eval (https://kittygram-oauth.stackblitz.io/turbo_modules/@angular/fire@6.0.0/bundles/angular-fire.umd.js:262:26)

```

### Expected behavior

It should not ask to install `@firebase/app` as it is an internal dep. to Firebase JS SDK.

### Actual behavior

It alerted saying that `@firebase/app` is not installed and prompted to install it. Once I did, I threw the error mentioned above when I tried to call `this.afAuth.signInWithPopup(new auth.GoogleAuthProvider());`

I've raised an issue here https://github.com/angular/angularfire/issues/2390 but most probably it has something to do with StackBlitz.

**Comment by purplem1lk** [comment]
Thank you for your patience - I have attached a screenshot of what I see when I click your project link. This issue is resolved based on the comments in (https://github.com/angular/angularfire/issues/2390). If your issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
 
![Screen Shot 2021-05-23 at 1 46 32 PM](https://user-images.githubusercontent.com/49956513/119270961-4c6f8980-bbcd-11eb-8f15-3fb6399faf63.png)
