### ISSUE TITLE
missing  src/tsconfig.app.json in synchronized repository

### ISSUE THREAD

**Issue by ElyesChine** [stackblitz/core#1230]
Hello 
I've created this project on stackblitz and then connected it to a github repository (create repo and push)

When I clone the repository on my machine and run 

> npm install

> npm start

I get

```
PS C:\Users\Elyes\projet\projet-frontend> npm start                                                                                                                                             
 angular@0.0.0 start C:\Users\Elyes\projet\projet-frontend
> ng serve

ENOENT: no such file or directory, stat 'C:\Users\Elyes\projet\projet-frontend\src\tsconfig.app.json'
Error: ENOENT: no such file or directory, stat 'C:\Users\Elyes\projet\projet-frontend\src\tsconfig.app.json'
    at Object.statSync (fs.js:915:3)
    at AngularCompilerPlugin._setupOptions (C:\Users\Elyes\projet\projet-frontend\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:93:16)
    at new AngularCompilerPlugin (C:\Users\Elyes\projet\projet-frontend\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:53:14)
    at _createAotPlugin (C:\Users\Elyes\projet\projet-frontend\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models\webpack-configs\typescript.js:41:12)
    at Object.getNonAotConfig (C:\Users\Elyes\projet\projet-frontend\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models\webpack-configs\typescript.js:47:19)
    at BrowserBuilder.buildWebpackConfig (C:\Users\Elyes\projet\projet-frontend\node_modules\@angular-devkit\build-angular\src\browser\index.js:84:37)
    at DevServerBuilder.buildWebpackConfig (C:\Users\Elyes\projet\projet-frontend\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:111:46)
    at MergeMapSubscriber.project (C:\Users\Elyes\projet\projet-frontend\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:38:40)
    at MergeMapSubscriber._tryNext (C:\Users\Elyes\projet\projet-frontend\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (C:\Users\Elyes\projet\projet-frontend\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (C:\Users\Elyes\projet\projet-frontend\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\Subscriber.js:67:18)
    at TapSubscriber._next (C:\Users\Elyes\projet\projet-frontend\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\tap.js:65:26)
    at TapSubscriber.Subscriber.next (C:\Users\Elyes\projet\projet-frontend\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (C:\Users\Elyes\projet\projet-frontend\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
    at InnerSubscriber._next (C:\Users\Elyes\projet\projet-frontend\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (C:\Users\Elyes\projet\projet-frontend\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\Subscriber.js:67:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Elyes\AppData\Roaming\npm-cache\_logs\2020-05-08T05_59_42_115Z-debug.log`
```

It's only when I download the project as a zip from the web ui and then extract that I get tsconfig.app.json where it is supposed to be 

Shouldn't src/tsconfig.app.json be there , in the synchronized repository in the first place ?

**Comment by arikanorh** [comment]
Yeah i also have this problem. I manually create for workaround

**Comment by arikanorh** [comment]
Also environments folder is completely missing even if the angular.json file refers to this folder as file replacements

**Comment by godzzo** [comment]
and missing also from index.html :
<base href="/">

**Comment by EzequielCaste** [comment]
> Yeah i also have this problem. I manually create for workaround

I'm having the same issue. How did you manage to correct this ?

**Comment by CurtisDS** [comment]
This is 2 years old and still not updated? Is it that big of a deal to add the file to the default project? Its obviously easily fixed if you manually create the file yourself but its a hassle to do for every angular project.
