### ISSUE TITLE
Firebase deployment issues: Failed to decode downloaded font, OTS parsing error

### ISSUE THREAD

**Issue by weilies** [stackblitz/core#1254]
I was able to develop in StackBlitz without any console warning or error. But after i deployed to firebase, i got 2 warnings and 1 error

Warning 1
```
Failed to decode downloaded font: <URL>
fireforgez.firebaseapp.com/:1 Failed to decode downloaded font: https://fireforgez.firebaseapp.com/fonts/primeicons.ttf
```

Warning 2
`OTS parsing error: invalid version tag
`
Error
```
HttpErrorResponse
error:
error: SyntaxError: Unexpected token < in JSON at position 0 at JSON.parse (<anonymous>) at XMLHttpRequest.onLoad (https://fireforgez.firebaseapp.com/turbo_modules/@angular/common@9.1.9/bundles/common-http.umd.js:1390:55) at ZoneDelegate.invokeTask (https://fireforgez.firebaseapp.com/turbo_modules/zone.js@0.10.3/dist/zone.js:411:35) at Object.onInvokeTask (https://fireforgez.firebaseapp.com/turbo_modules/@angular/core@9.1.9/bundles/core.umd.js:19397:37) at ZoneDelegate.invokeTask (https://fireforgez.firebaseapp.com/turbo_modules/zone.js@0.10.3/dist/zone.js:410:40) at Zone.runTask (https://fireforgez.firebaseapp.com/turbo_modules/zone.js@0.10.3/dist/zone.js:178:51) at ZoneTask.invokeTask [as invoke] (https://fireforgez.firebaseapp.com/turbo_modules/zone.js@0.10.3/dist/zone.js:493:38) at invokeTask (https://fireforgez.firebaseapp.com/turbo_modules/zone.js@0.10.3/dist/zone.js:1633:18) at XMLHttpRequest.globalZoneAwareCallback (https://fireforgez.firebaseapp.com/turbo_modules/zone.js@0.10.3/dist/zone.js:1670:25)
text: "<html><head><script src="https://c.staticblitz.com/d/webcontainer.b8cb3965d30f7aa9372.js"></script><script src="/vendor.bundle.js?1590765573823"></script><script src="/app.bundle.js?1590765573823"></script></head><body></body></html>"
__proto__: Object
headers: HttpHeaders {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
message: "Http failure during parsing for https://fireforgez.firebaseapp.com/assets/i18n/en.json"
name: "HttpErrorResponse"
ok: false
status: 200
statusText: "OK"
url: "https://fireforgez.firebaseapp.com/assets/i18n/en.json"
```

Here is my angular.json
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "demo": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/demo",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css",
              "node_modules/primeicons/primeicons.css",
              "node_modules/primeng/resources/themes/nova-light/theme.css",
              "node_modules/primeng/resources/primeng.min.css",
              "../node_modules/quill/dist/quill.core.css",
              "../node_modules/quill/dist/quill.snow.css"
            ],
            "scripts": [
              "../node_modules/quill/dist/quill.js"
            ]
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "demo:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "demo:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "demo:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "styles.css",
              "node_modules/primeicons/primeicons.css",
              "node_modules/primeng/resources/themes/nova-light/theme.css",
              "node_modules/primeng/resources/primeng.min.css",
              "../node_modules/quill/dist/quill.core.css",
              "../node_modules/quill/dist/quill.snow.css"
            ],
            "scripts": [
              "../node_modules/quill/dist/quill.js"
            ],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "demo"
}
```

Package.json, i only included additional package like ngx-translate, primeNG
```
  "dependencies": {
    "@angular/animations": "9.1.9",
    "@angular/cdk": "9.2.4",
    "@angular/common": "9.1.9",
    "@angular/compiler": "9.1.9",
    "@angular/core": "9.1.9",
    "@angular/forms": "9.1.9",
    "@angular/material": "9.2.4",
    "@angular/platform-browser": "9.1.9",
    "@angular/platform-browser-dynamic": "9.1.9",
    "@angular/router": "9.1.9",
    "@ngx-translate/core": ">=11.0.0",
    "@ngx-translate/http-loader": "^4.0.0",
    "chart.js": "2.9.3",
    "core-js": "2.6.11",
    "primeicons": "3.0.0",
    "primeng": "9.1.0",
    "quill": "1.3.7",
    "rxjs": "6.5.5",
    "tslib": "1.13.0",
    "zone.js": "0.10.3"
  },
```

Is there any configuration i missed out? Thanks for the support! :)

**Comment by weilies** [comment]
hi StackBlitz supports and experts (@EricSimons 🥇 ),
I have composed list of breaks with [comprehensive logs i encountered in StackBlitz to StackOverflow.](https://stackoverflow.com/questions/62127323/unable-to-load-language-json-and-css-files-in-firebase-hosting)

Hope it helps in fixing the issues.

Thanks! Love you guys!

**Comment by EricSimons** [comment]
Hey @weilies! We love you too man!

So unfortunately I think you'll need to clone your project locally & deploy to firebase using their CLI. Our firebase integration is currently in a "beta" state and currently doesn't support some of the more complex cases which is what I think is going on here.

We're rolling out some updates to this over the summer that should bridge the gap between local & SB but it'll likely take a bit. Another option btw is to connect your project to a GitHub repo and use [this action](https://github.com/marketplace/actions/github-action-for-firebase) to automatically trigger deploys on every commit

**Comment by weilies** [comment]
hi @EricSimons , it might take a couple of months for slow learner like me to figure out the whole working flow. Does your team have a target date to sort of the deployment issues? I mean i could be your tester. Once it's deploy flow is solid, SB will get more subscribers. 

I am sure many scared away by SB, everything was running so good but end up stuck at the deployment step. I didn't chose MS Visual Studio code but StackBlitz about a year ago. Hard to say goodbye LOL!

**Comment by weilies** [comment]
@EricSimons , let me share some of my thought. Firstly, StackBlitz is TOO COOL and people are trying to build packages, dependencies and run on top of "StackBlitz's standard".

It not just gave me, the package builder (e.g. quill editor), it works in SB means it surely work in Firebase. That's why many of them even provide sample with SB link (but they NEVER test them in Firebase).

I noticed this because i fork their SB sample report to mine, then deploy to Firebase and it straightaway failed. We are too depending on SB coz it's too easy to use. It leads ignored the concern of FB deployment. I only notice the crucial of the deployment flow after i half way done of my project in SB.

I hit couple of package error (not just versioning, but the path) One thing really help me is the logs. They gave the clue and without them, i can never solve it. I think SB would be greatly reduce the support effort as we could get insight on deployment error. We could self-sufficient to debug our own instead of keep bugging u LOL.

I don't mean to complain but to share my thought on SB.
