### ISSUE TITLE
Vite 2.6 beta failed to run on StackBlitz

### ISSUE THREAD

**Issue by antfu** [stackblitz/core#1615]
### **Description of Bug**

Vite 2.6 beta failed to run on StackBlitz

### **Steps to Reproduce**

Using https://vite.new but change the vite's version to 2.6.0-beta.2

https://stackblitz.com/edit/vite-at4tg5

## **Error Log**

Error on StackBlitz

```bash
syntaxError: Invalid or unexpected token
    at __global_eval__ (https://vite-at4tg5.jw.staticblitz.com/blitz.fa2fa735bbb029186c23972eb56445ed5c5fdef5.js:8:19917)
    at _0x5ca3df (https://vite-at4tg5.jw.staticblitz.com/blitz.fa2fa735bbb029186c23972eb56445ed5c5fdef5.js:11:126610)
    at _0x4a7b31._compile (https://vite-at4tg5.jw.staticblitz.com/blitz.fa2fa735bbb029186c23972eb56445ed5c5fdef5.js:11:124833)
    at _0x2beabf (https://vite-at4tg5.jw.staticblitz.com/blitz.fa2fa735bbb029186c23972eb56445ed5c5fdef5.js:11:122673)
    at wrapSafe (https://vite-at4tg5.jw.staticblitz.com/blitz.fa2fa735bbb029186c23972eb56445ed5c5fdef5.js:6:166884)
```

**Additional Context/Questions**

Probably due to esbuild v0.13 changes:

- https://github.com/vitejs/vite/pull/5041
- https://github.com/evanw/esbuild/blob/master/CHANGELOG.md#0130

**Comment by sulco** [comment]
Thank you @antfu for reporting this! We've just deployed the fix and I can confirm the repro is working now.

Closing now, but please reopen if this by any chance reappears.

**Comment by MaggieLu** [comment]
I met the same problem today. Failed to run start command for vite.  
Steps to reproduce: open https://stackblitz.com/edit/vite-drxjme 
![image](https://user-images.githubusercontent.com/10663057/138069153-2627a80c-513d-411e-ac34-6b6758ed14c5.png)
