### ISSUE TITLE
Stackblitz preview doesn't work on Chrome

### ISSUE THREAD

**Issue by danmana** [stackblitz/core#162]
Live reload/ preview doesn't work in Chrome (Version 61.0.3163.100 (Official Build) (64-bit)).

Steps to reproduce:
1. create a new project (ex: https://stackblitz.com/edit/angular-ta3yfy)
2. the preview section doesn't load
 (open in a new window works, but without live reload)

```
_relay_:10 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://angular-vxbayq.stackblitz.io/_relay_:10:7
    at https://angular-vxbayq.stackblitz.io/_relay_:43:7
(anonymous) @ _relay_:10
(anonymous) @ _relay_:43
preview-7160e757d494cd480578.js:1 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.255 (https://static.stackblitz.com/assets/packs/preview-7160e757d494cd480578.js:1:104517)
    at t (https://static.stackblitz.com/assets/packs/preview-7160e757d494cd480578.js:1:101)
    at Object.1003 (https://static.stackblitz.com/assets/packs/preview-7160e757d494cd480578.js:1:4791)
    at t (https://static.stackblitz.com/assets/packs/preview-7160e757d494cd480578.js:1:101)
    at Object.254 (https://static.stackblitz.com/assets/packs/preview-7160e757d494cd480578.js:1:103669)
    at t (https://static.stackblitz.com/assets/packs/preview-7160e757d494cd480578.js:1:101)
    at Object.439 (https://static.stackblitz.com/assets/packs/preview-7160e757d494cd480578.js:1:116545)
    at t (https://static.stackblitz.com/assets/packs/preview-7160e757d494cd480578.js:1:101)
    at Object.447 (https://static.stackblitz.com/assets/packs/preview-7160e757d494cd480578.js:1:117808)
    at t (https://static.stackblitz.com/assets/packs/preview-7160e757d494cd480578.js:1:101)
255 @ preview-7160e757d494cd480578.js:1
t @ preview-7160e757d494cd480578.js:1
1003 @ preview-7160e757d494cd480578.js:1
t @ preview-7160e757d494cd480578.js:1
254 @ preview-7160e757d494cd480578.js:1
t @ preview-7160e757d494cd480578.js:1
439 @ preview-7160e757d494cd480578.js:1
t @ preview-7160e757d494cd480578.js:1
447 @ preview-7160e757d494cd480578.js:1
t @ preview-7160e757d494cd480578.js:1
n.10 @ preview-7160e757d494cd480578.js:1
(anonymous) @ preview-7160e757d494cd480578.js:1
(index):11 Uncaught ReferenceError: _preboot is not defined
    at (index):11
    at (index):11
```

**Comment by ssuperczynski** [comment]
@danmana It works for me

**Comment by EricSimons** [comment]
@danmana can you try disabling chrome extensions and see if that fixes it?

**Comment by danmana** [comment]
@EricSimons  Same in incognito mode without extensions.

I found the issue: aparently having the following setting enabled blocks both cookies and local storage

chrome://settings/content/cookies
```
Block third-party cookies
Prevent third-party websites from saving and reading cookie data
```

The js file in question is served from https://angular-ta3yfy.stackblitz.io
The main window is loaded from https://stackblitz.com/edit/angular-ta3yfy
Since these are two different domains, Chrome blocks cookies and local storage access.

Same happens when the originating call comes from:  https://static.stackblitz.com/assets/packs/preview-7160e757d494cd480578.js

I'm not sure how this should be addressed, or even if it's possible while keeping each project sandboxed. Perhaps the window url should also be on the project domain? (ex: https://angular-ta3yfy.stackblitz.io/edit)

Right now the only alternative is running with 3rd party cookies enabled, which some users might not want to do.

**Comment by jlamby** [comment]
Same problem with Firefox (obviously) when 3rd party cookies are disabled

**Comment by cvietor** [comment]
thx @danmana 
a quick workaround without enabling 3rd party cookies globally is to add an exception to stackblitz.io

-> chrome://settings/content/cookies
-> Allow: 
`[*.]stackblitz.io`

**Comment by lordKnighton** [comment]
Thanks @cvietor a verbatim solution 👍

**Comment by alexsasharegan** [comment]
Is there any way to detect that 3rd party cookies is disabled? It would be amazingly nice if you could sniff this and provide a helpful message like this fix: https://github.com/stackblitz/core/issues/162#issuecomment-357656965

**Comment by trusktr** [comment]
For reference, if 3rd party stuff is not allowed, here's how to make it work in Chrome for the specific sites (stackblitz in this case):

Click the cookie in the address bar:

<img width="509" alt="screen shot 2018-10-03 at 11 29 35 am" src="https://user-images.githubusercontent.com/297678/46431052-a3b04b00-c6ff-11e8-8a70-5edd48d3da1e.png">

Click "Show cookies and other site data..." which takes you to:

<img width="786" alt="screen shot 2018-10-03 at 11 30 50 am" src="https://user-images.githubusercontent.com/297678/46431135-d5c1ad00-c6ff-11e8-9e79-5ff78fc87fe1.png">

Switch to the "Blocked" tab, then select the cookies to allow. 

In the case of stackblitz, you need to allow staticblitz.com and the specific subdomain for the blitz you're working on. In my case, it was these two:

<img width="447" alt="screen shot 2018-10-03 at 11 31 54 am" src="https://user-images.githubusercontent.com/297678/46431216-16212b00-c700-11e8-9783-72d598dd772b.png">

Then refresh, and it will work.

Note, you don't need to allow the other ones, and it will still work. F.e. I did not allow these ones:

<img width="565" alt="screen shot 2018-10-03 at 11 33 52 am" src="https://user-images.githubusercontent.com/297678/46431271-3bae3480-c700-11e8-94c8-b3332a73142d.png">

**Comment by alexsasharegan** [comment]
It's been a while since this, but I remember it being easy to correct the issue. I just remember being very confused for a while as to why things weren't working.

**Comment by Sixtisam** [comment]
Isn't this going to be fixed? Yeah, there exists a workaround for that, but the issue was created _over a year ago_ and there is still no proper solution for this?

**Comment by beeman** [comment]
There seem to be issues with getting it to work in Brave too. You can work around it by disabling the shield for the domain stackblitz.com. 

![image](https://user-images.githubusercontent.com/36491/49776987-7f0ebb80-fccc-11e8-9b2a-6f973c2209d0.png)

Thanks to @markpieszak for informing be about the issue!

**Comment by tekgeist-inc** [comment]
So.. i would have to allow them to run ads, 3rd party cookies and tracking on my machine?
No thanks. Seems like i need to GTFO here then.
And i seriously question anyones competence who choses to present their official code samples this way.

**Comment by tekgeist-inc** [comment]
Just use plunker instead. It works without requiring to enable 3rd party spyware.

**Comment by Otolone** [comment]
Thanks at cvietor

**Comment by tanybt51** [comment]
that's what worked for me:
go to : `chrome://settings/content/cookies`

![image](https://user-images.githubusercontent.com/33543234/60418236-1a289d80-9beb-11e9-8256-38850a2c718e.png)

**Comment by Pyrdacor** [comment]
> There seem to be issues with getting it to work in Brave too. You can work around it by disabling the shield for the domain stackblitz.com.
> 
> ![image](https://user-images.githubusercontent.com/36491/49776987-7f0ebb80-fccc-11e8-9b2a-6f973c2209d0.png)
> 
> Thanks to @MarkPieszak for informing be about the issue!

Ran into the same problem. You can leave the shields up but change "Cookie Control" to "Allow3rd Party Cookies". It's a workaround. Maybe this could be fixed in the future?

**Comment by abhishek0196** [comment]
Thanks @cvietor  it worked like charm !!!

**Comment by scott859** [comment]
Another shout-out to @cvietor for his solution!

**Comment by dusanbass** [comment]
This doesn't work for chrome Version 83.0.4103.116 (Official Build) (64-bit)
I don't have any add block or similar. 
The preview window is blank no matter which project I open.

**Comment by agroupp** [comment]
Same here, it stopped working few days ago, before was ok.

**Comment by dusanbass** [comment]
Hey, here's what worked for me in the end:

Logged out out of all gmails.
Cleared cache of the Chrome.
Logged in into only one gmail for github.

Works now. Even with ad block.

**Comment by luisjunco** [comment]
@cvietor 

the domain seems to have changed from _.io_ to _.com_. It'd be great if you can pls update your [wonderful answer](https://github.com/stackblitz/core/issues/162#issuecomment-357656965) to reflect that change.

> a quick workaround without enabling 3rd party cookies globally is to add an exception to stackblitz.io / stackblitz.com

-> chrome://settings/content/cookies
-> Allow -> Add:
`[*.]stackblitz.io`
`[*.]stackblitz.com`

**Comment by AndyOGo** [comment]
Same here.
App won't start up in Chrome, but in Firefox.

**Comment by AMBudnik** [comment]
Chrome 89 - still enabling cookies for the `[*.]stackblitz.com` doesn't help...

**Comment by J-Siu** [comment]
Firefox stable(88.0.1) and nightly(90.0a1) won't start preview panel.

**Comment by fnky** [comment]
The temporary fix is to enable cookies for `[*.]stackblitz.io` (note the `.io` TLD and not `.com`) from `brave://settings/cookies`.

**Comment by avshin12** [comment]
FYI `[*.]stackblitz.com` worked for me - spent 10 minutes on this.

**Comment by pixelbucket-dev** [comment]
Just a small helper from my side, since I struggled to fix this.

1. I deactivated all extensions that potentially block content/cookies
2. Then I found I had set the mode of `Enhanced Tracking Protection` to "Strict".
3. Change the mode to "Standard" and it works, alternatively use the "Custom" mode, but youy must keep the option `Cross-site tracking cookies — includes social media cookies` set.


<img width="682" alt="Screenshot 2021-07-26 at 19 02 01" src="https://user-images.githubusercontent.com/12937991/127037856-3f12c906-055c-42a9-bea7-e8a5b00a14db.png">

<img width="677" alt="Screenshot 2021-07-26 at 19 04 10" src="https://user-images.githubusercontent.com/12937991/127037898-d4cb2027-3f6b-40cc-96df-2827dc26dc2e.png">

Also, for me `Delete cookies and site data when Firefox is closed` was unticked, so not the issue in my case.

**Comment by thykka** [comment]
Softening the browser's security settings hardly seems like a solution. There are good reasons to block 3rd party cookies. IMO this should be resolved without resorting to forcing the user to open their browser for 3rd party tracking.

**Comment by pixelbucket-dev** [comment]
I totally agree. It's quite a dubious practice to force such cookies.

**Comment by michaelbazos** [comment]
@Sebi2020 

In Chrome settings, search for cookies. Or go straight to chrome://settings/cookies

Under _"Sites that can always use cookies"_ click _Add_

Do **either** of the following:

- Variant 1: type **[*.]stackblitz.com**, and **enable _"Including third-party cookies on this site"_**
- Variant 2: type **[*.]stackblitz.io**, and **do not enable _"Including third-party cookies on this site"_**

_stackblitz.io_ is the domain used by the webserver, the second variant is therefore more restrictive as any other third-party cookies would still be blocked.

**Comment by Nezteb** [comment]
Nothing works for me.

macOS 11.6.2
Chrome Version 97.0.4692.71 (Official Build) (x86_64)

My cookie settings:
<img width="670" alt="Screen Shot 2022-01-14 at 3 21 14 PM" src="https://user-images.githubusercontent.com/3588798/149586906-4c56cc3d-4de3-4e4f-a9a3-a9e6cec14f45.png">

No cookies are being blocked:
<img width="1097" alt="Screen Shot 2022-01-14 at 3 19 48 PM" src="https://user-images.githubusercontent.com/3588798/149586933-f4982977-c1fb-4156-b64b-7991bf9759c1.png">

Console errors:
<img width="1265" alt="Screen Shot 2022-01-14 at 3 20 43 PM" src="https://user-images.githubusercontent.com/3588798/149586951-aff7a7d2-3902-4906-9246-e33e05c00321.png">

I've tried with all plugins disabled, incognito, restarting the browser, trying several different Stackblitz examples, and nothing works.

**Comment by Nezteb** [comment]
Okay I assumed that when I had uBlock Origin turned off that it would actually... turn off everything. But no, apparently it does not.

In order to resolve this I had to go into the "My rules" tab of uBlock Origin's settings and add these:
```
no-scripting: stackblitz.com false
no-scripting: stackblitz.io false
no-scripting: local.webcontainer.io false
```

**Comment by siberia3** [comment]
Remember to reload the page, otherwise you will think that (allowing cookies for *.io and *.com) did not solve the issue

**Comment by vaibhavnirmal10** [comment]
> Nothing works for me.
> 
> macOS 11.6.2 Chrome Version 97.0.4692.71 (Official Build) (x86_64)
> 
> My cookie settings: <img alt="Screen Shot 2022-01-14 at 3 21 14 PM" width="670" src="https://user-images.githubusercontent.com/3588798/149586906-4c56cc3d-4de3-4e4f-a9a3-a9e6cec14f45.png">
> 
> No cookies are being blocked: <img alt="Screen Shot 2022-01-14 at 3 19 48 PM" width="1097" src="https://user-images.githubusercontent.com/3588798/149586933-f4982977-c1fb-4156-b64b-7991bf9759c1.png">
> 
> Console errors: <img alt="Screen Shot 2022-01-14 at 3 20 43 PM" width="1265" src="https://user-images.githubusercontent.com/3588798/149586951-aff7a7d2-3902-4906-9246-e33e05c00321.png">
> 
> I've tried with all plugins disabled, incognito, restarting the browser, trying several different Stackblitz examples, and nothing works.

https://github.com/stackblitz/core/issues/162#issuecomment-1488988506

`[*.]stackblitz.com`

**Comment by rajkishancode** [comment]
> thx @danmana a quick workaround without enabling 3rd party cookies globally is to add an exception to stackblitz.io
> 
> -> chrome://settings/content/cookies -> Allow -> Add: `[*.]stackblitz.io`

Thank you a ton.

**Comment by scottwalter-nice** [comment]
I've added all these and still get rejected

<img width="613" alt="CleanShot 2023-04-14 at 08 31 04@2x" src="https://user-images.githubusercontent.com/59891581/232057522-d6de5bc1-bdc2-4cab-a7ad-ce1d4ddd20cf.png">

**Comment by atengberg** [comment]
Issue is also with Brave (as a Chrome fork). The above worked, but had to prefix with `https://` and restart Brave.

I'd suggest detecting if the preview has the initial expected output, and if not adding a note about adding the above as recommended. Otherwise this service is preferable.

**Comment by fireflysemantics** [comment]
I just added the exceptions mentioned in the documentation and still no love for me.   When I click "Open Project in Separate Tab" it just spins ... I asked about it on SO also ...

https://stackoverflow.com/questions/77083782/getting-stackblitz-to-run-in-separate-tab

**Comment by kc0tlh** [comment]
@fireflysemantics would you be available to hop on a call with our eng team to troubleshoot? If so, please reach out to hello@stackblitz.com I and I will jump in to coordinate!

**Comment by fireflysemantics** [comment]
@kc0tlh sure.  My name is Ole Ersoy... Just so you know who's emailing you... I'll send you an email now.
