### ISSUE TITLE
Parcel 2 doesn't work

### ISSUE THREAD

**Issue by CyberAP** [stackblitz/core#1694]
### **Description of Bug**

Using Parcel 2 doesn't work in Stackblitz.

### **Steps to Reproduce**

1. Use Parcel 2 to serve your project

Example project: https://stackblitz.com/edit/react-parcel-starter-tkzehh?file=package.json
Another example: https://stackblitz.com/edit/github-i78mcj?file=package.json

### **Expected Behavior**

Project should be served just fine as with Parcel 1.

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by adminy** [comment]
+1
```
❯ npx parcel index.html
Error: not implemented
    at _0x5a6b74 (https://PROJECT.w.staticblitz.com/blitz.RAND.js:11:5264)
    at process.dlopen (https://PROJECT.w.staticblitz.com/blitz.RAND.js:11:157841)
    at Object.Module._extensions..node (https://PROJECT.w.staticblitz.com/blitz.RAND.js:6:168613)
    at Module.load (https://PROJECT.w.staticblitz.com/blitz.RAND.js:6:166317)
    at Function.Module._load (https://PROJECT.w.staticblitz.com/blitz.v.js:6:163857)
    at Module.require (https://PROJECT.w.staticblitz.com/blitz.RAND.js:6:166635)
    at i (https://PROJECT.w.staticblitz.com/blitz.RAND.js:6:427483)
    at _0x67bb30 (https://PROJECT.w.staticblitz.com/blitz.RAND.js:11:114034)
    at Object.eval (/home/projects/PROJECT/node_modules/@parcel/fs-search/index.js:19:20)
    at Object.function (https://PROJECT.w.staticblitz.com/blitz.RAND.js:11:114407)
```
