### ISSUE TITLE
CORS exception

### ISSUE THREAD

**Issue by cjkeilig** [stackblitz/core#1740]
### **Description of Bug**
Angular intl library not loading because of CORS exception

### **Steps to Reproduce**

1. [Go to https://stackblitz.com/run/?file=package.json](https://stackblitz.com/edit/ojhvaq--run?file=package.json).
2. Update all packages
3. Downgrade core-js back to 2.6.12 

### **Expected Behavior**
Angular intl loads without CORS exception

### **Screenshots/Screencast**
Access to fetch at 'https://t.staticblitz.com/v2021.11.09/@progress/kendo-angular-intl@3.1.2' from origin 'https://stackblitz.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by geromegrignon** [comment]
Changes occurred between Angular 9 and the current Angular 13 version, requiring more than just a dependencies update.

Apart from your error message, there is another one displayed:

```ts
preview-a214a06f7a20.js:2 Error: It looks like your application or one of its dependencies is using i18n.
Angular 9 introduced a global `$localize()` function that needs to be loaded.
Please run `ng add @angular/localize` from the Angular CLI.
(For non-CLI projects, add `import '@angular/localize/init';` to your `polyfills.ts` file.
For server-side rendering applications add the import to your `main.server.ts` file.)
    at _global.$localize (yysjf5--run.stackblitz.io/turbo_modules/@angular/core@13.2.2/fesm2015/core.mjs:28852:15)
    at consts (ng:///e.js:269:18)
    at createTView (yysjf5--run.stackblitz.io/turbo_modules/@angular/core@13.2.2/fesm2015/core.mjs:9719:60)
    at getOrCreateTComponentView (yysjf5--run.stackblitz.io/turbo_modules/@angular/core@13.2.2/fesm2015/core.mjs:9694:28)
    at addComponentLogic (yysjf5--run.stackblitz.io/turbo_modules/@angular/core@13.2.2/fesm2015/core.mjs:10465:19)
    at instantiateAllDirectives (yysjf5--run.stackblitz.io/turbo_modules/@angular/core@13.2.2/fesm2015/core.mjs:10306:13)
    at createDirectivesInstances (yysjf5--run.stackblitz.io/turbo_modules/@angular/core@13.2.2/fesm2015/core.mjs:9657:5)
    at ɵɵelementStart (yysjf5--run.stackblitz.io/turbo_modules/@angular/core@13.2.2/fesm2015/core.mjs:14550:9)
    at AppComponent_Template (ng:///AppComponent.js:10:9)
    at executeTemplate (yysjf5--run.stackblitz.io/turbo_modules/@angular/core@13.2.2/fesm2015/core.mjs:9628:9)
   ```
   
   Your problem is directly related to the sample created by Kendo, not about Stackblitz itself.
   
   You can find the related issue tracker there: https://github.com/telerik/kendo-angular

**Comment by cjkeilig** [comment]
Ok, thank you
