### ISSUE TITLE
Socket hang up - CORS

### ISSUE THREAD

**Issue by keystroke** [stackblitz/core#2121]
### **Description of Bug**
Making a fetch call to endpoint without cors header on response fails with socket hang up error.

Code like this:

~~~js
import fetch from 'node-fetch';

(async () => {
  const response = await fetch(
    'https://api.bethesda.net/mods/ugc-workshop/content/get?content_id=4247794'
  );
})().catch((error) => console.error(error));
~~~

Will result in this error:

~~~shell
$ node index.mjs
FetchError: request to https://api.bethesda.net/mods/ugc-workshop/content/get?content_id=4247794 failed, reason: socket hang up
    at ClientRequest.eval (file:///home/projects/socket-hang-up-cors/node_modules/node-fetch/src/index.js:136:11)
    at EventEmitter.emit (https://socket-hang-up-cors-xb4455vm.w.staticblitz.com/blitz.8710b01cd3456444b4ea0bc080c4276768dc0bc7.js:6:155574)
    at TLSSocket.socketOnEnd (https://socket-hang-up-cors-xb4455vm.w.staticblitz.com/blitz.8710b01cd3456444b4ea0bc080c4276768dc0bc7.js:6:1087102)
    at EventEmitter.emit (https://socket-hang-up-cors-xb4455vm.w.staticblitz.com/blitz.8710b01cd3456444b4ea0bc080c4276768dc0bc7.js:6:155690)
    at endReadableNT (https://socket-hang-up-cors-xb4455vm.w.staticblitz.com/blitz.8710b01cd3456444b4ea0bc080c4276768dc0bc7.js:6:660465)
    at _0x48a976 (https://socket-hang-up-cors-xb4455vm.w.staticblitz.com/blitz.8710b01cd3456444b4ea0bc080c4276768dc0bc7.js:15:148200)
    at https://socket-hang-up-cors-xb4455vm.w.staticblitz.com/blitz.8710b01cd3456444b4ea0bc080c4276768dc0bc7.js:15:147949 {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: undefined
}
~~~

Developer tools shows this error:

Access to fetch at 'https://api.bethesda.net/mods/ugc-workshop/content/get?content_id=4247794' from origin 'https://socket-hang-up-cors-xb4455vm.w.staticblitz.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
​ FetchError: request to https://api.bethesda.net/mods/ugc-workshop/content/get?content_id=4247794 failed, reason: socket hang up

### **Steps to Reproduce**

1. Go to https://stackblitz.com/edit/socket-hang-up-cors?file=index.mjs
2. the startup script should run, making a fetch call to some endpoint.
3. Get a socket hang up error in the console
4. Developer tools shows CORS error from remote endpoint

### **Expected Behavior**
CORS needs to work from server context.

**Additional Context/Questions**
Is CORS intended to be supported? I saw in tweet on release that a proxy was going to be added to deal with CORS errors running in browser contexts, is there any info on that or on when it would be supported (if necessary)?

**Comment by keystroke** [comment]
This tweet indicated there would be a CORS proxy? https://twitter.com/ericsimons40/status/1507492185175822337
