### ISSUE TITLE
Angular - Unable to install packages

### ISSUE THREAD

**Issue by Magnabatt** [stackblitz/core#2265]
Hi, I have recently started using StackBlitz and for the first week I was able to install packages on my Angular app's. However since Thursday the 12th of Jan the package install just keeps getting stuck on "RUNNING NGCC" as per my screen shoot. 
<img width="1273" alt="error1" src="https://user-images.githubusercontent.com/29217513/212572589-d1a37238-9082-4874-bcb6-0a21a8a87c50.PNG">

Looking at the error, there seems to be an issue with the web container. Can you please investigate? 

`Uncaught (in promise) SyntaxError: Cannot use 'import.meta' outside a module (at webcontainer.bfee0704b2dee6f4f820d00343609f2869551d0f.js:15:5474)
    at eval (<anonymous>)
    at Qt (webcontainer.bfee0704b2dee6f4f820d00343609f2869551d0f.js:15:30145)
    at webcontainer.bfee0704b2dee6f4f820d00343609f2869551d0f.js:15:38799
    at U (webcontainer.bfee0704b2dee6f4f820d00343609f2869551d0f.js:15:13565)
    at webcontainer.bfee0704b2dee6f4f820d00343609f2869551d0f.js:15:13207
    at Object.eval (typescript.ts:43:25)
    at eval (typescript_translator.ts:33:1)
    at eval (typescript_translator.ts:33:1)
    at eval (<anonymous>)
    at Qt (webcontainer.bfee0704b2dee6f4f820d00343609f2869551d0f.js:15:30145)
l @ webcontainer.bfee0704b2dee6f4f820d00343609f2869551d0f.js:15
(anonymous) @ webcontainer.bfee0704b2dee6f4f820d00343609f2869551d0f.js:15`

**Comment by markwhitfeld** [comment]
Fix was released on Monday and there has been no recurrence.
This should be resolved now. Closing issue.
