### ISSUE TITLE
Find on stackblitz but Error after deploy on firebase.

### ISSUE THREAD

**Issue by kimkimjungjp** [stackblitz/core#2712]
I just make a vanilla js on stackblitz to connect firebase realtime data base and it work find.
but after deploy in error on firebase hosting.

Uncaught (in promise) SyntaxError: Unexpected identifier '$'
    at eval (<anonymous>)
    at Qt (webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:15:30145)
    at webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:15:38799
    at U (webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:15:13565)
    at webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:15:13207
    at Object.eval (/turbo_modules/@firebase/component@0.6.4/dist/esm/index.esm2017.js:4:16)
    at eval (/turbo_modules/@firebase/component@0.6.4/dist/esm/index.esm2017.js:317:4)
    at eval (/turbo_modules/@firebase/component@0.6.4/dist/esm/index.esm2017.js:318:3)
    at eval (<anonymous>)
    at Qt (webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:15:30145)

here is url https://test-d298a.web.app/

**Comment by kimkimjungjp** [comment]
https://stackblitz.com/edit/js-k4beby?file=README.md
