### ISSUE TITLE
Syntax is not highlighted in .vue files

### ISSUE THREAD

**Issue by bushido2014** [stackblitz/core#2747]
### Describe the bug

Syntax is not highlighted in .vue files in Nuxt

### Link to the blitz that caused the error

https://stackblitz.com/edit/nuxt-starter-nf7ym6?file=pages%2Fgames%2F[id].vue

### Steps to reproduce

![2023-09-28 13_34_47-nuxt3-pagination-example - StackBlitz](https://github.com/stackblitz/webcontainer-core/assets/8748516/aa65014c-daca-4029-8bbf-70f676eddbae)

### Expected behavior

Syntax is not highlighted in .vue files in Nuxt

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![2023-09-28 13_34_47-nuxt3-pagination-example - StackBlitz](https://github.com/stackblitz/webcontainer-core/assets/8748516/0b6d2cbf-1f08-41ac-9232-1b807c1ba043)

### Platform

```
Browser name  = Chrome
Full version  = 117.0.0.0
Major version = 117
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 91531694,
  "usedJSHeapSize": 66530846,
  "jsHeapSizeLimit": 2127298560
}
Hash = 2486b441
```

**Comment by alexpopovme** [comment]
Same issue. It works sometimes when I open the projects but in most cases not.

**Comment by eisterman** [comment]
Same problem

**Comment by pracan** [comment]
It seems to be related to the error message :

client-47a5a5836f44a.js:2 Uncaught (in promise) Error: Near offset 31394: unexpected opened tag /dict ~~~
						<dict>
							<key>include</key>
							<st~~~
    at _ (client-47a5a5836f44a.js:2:1405318)
    at r (client-47a5a5836f44a.js:2:1407987)
    at t.parse (client-47a5a5836f44a.js:2:1408228)
    at client-47a5a5836f44a.js:2:1404552
    at t.parseRawGrammar (client-47a5a5836f44a.js:2:1404561)
    at Object.loadGrammar (client-47a5a5836f44a.js:2:2341520)
