### ISSUE TITLE
Pure HTML / CSS / JS doesn't work in new tab

### ISSUE THREAD

**Issue by evheniyrz** [stackblitz/core#2828]
### **Description of Bug**
The newly created project does not launch in a new browser tab.
an exception is displayed in the browser console.

Environment:
* Desktop Windows 10 64-bit v.22H2 build 19045.3570
* Browser - Google Chrome v. 119.0.6045.124 (64-bit)

### **Steps to Reproduce**

1. Create a new project - Pure HTML / CSS / JS
2. Click on 'Open in new tab' button - https://prnt.sc/yDg1wrxVy0sP
3. Open Google Chrome DevTools
`Uncaught (in promise) Error: Preset not sepcified in configuration
    at rt.<anonymous> (webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:8:207891)
    at Generator.next (<anonymous>)
    at webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:8:205947
    at new Promise (<anonymous>)
    at Z (webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:8:205684)
    at rt.config (webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:8:206973)
    at he.config (webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:8:232555)
    at Oe (preview-c97e327a318ca.js:2:582633)
    at Object.PREVIEW_INSTANTIATE_BUNDLE (preview-c97e327a318ca.js:2:583483)
    at preview-c97e327a318ca.js:2:563218`

### **Expected Behavior**
the project runs in a new browser tab successfully.

### **Screenshots/Screencast**
[If applicable, add screenshots to help explain your problem.](https://prnt.sc/7mM7E2KtbTN6)
![image](https://github.com/stackblitz/core/assets/42120738/9134805c-b36d-4003-bdc6-2e3b77715f31)

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by adrianbienias** [comment]
I encounter the same issue

**Comment by Reza-1** [comment]
I also experience the same issue on stackblitz.io

**Comment by teociaps** [comment]
I'm experiencing the same annoying issue.
I tried on:
- Chrome v. 120.0.6099.224 (64-bit)
- Firefox v. 121.0.1 (64-bit)
- Edge v. 120.0.2210.133 (64-bit)
