### ISSUE TITLE
Fails to clone repo in Codeflow editor

### ISSUE THREAD

**Issue by cjkirk09** [stackblitz/core#2848]
### description of the problem

When trying to open any personal repo (public or private) in the Codeflow editor, it hangs on the Booting WebContainer step.
Example repo, which is an unchanged clone of the Blank Js Project https://stackblitz.com/~/github.com/cjkirk09/js-lgzfka2
In the console, it shows an error cloning the github repo
```
ERR something went wrong: Failed to fetch index: https://g.staticblitz.com/v6.6/h/e/github.com/cjkirk09/js-lgzfka2/stream/tree/main
Body: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Something went wrong while cloning [github.com/cjkirk09/js-lgzfka2](chrome://devtools/content/webconsole/github.com/cjkirk09/js-lgzfka2).<br> &nbsp; &nbsp;at generateDotGitIndex (file:///var/task/src/lambda.mjs:126207:11)<br> &nbsp; &nbsp;at async doGenerateGitPayload (file:///var/task/src/lambda.mjs:126332:20)<br> &nbsp; &nbsp;at async load (file:///var/task/src/lambda.mjs:126404:7)<br> &nbsp; &nbsp;at async file:///var/task/src/lambda.mjs:126468:41</pre>
</body>
</html>
: Bt/</<@https://ide-corp.staticblitz.com/4f3918d67b0d0d6d912f5928adca1fb73bf3c67b/preload.js:2:552998
[workbench.web.main.js:199:29104](https://ide-corp.staticblitz.com/4f3918d67b0d0d6d912f5928adca1fb73bf3c67b/out/vs/workbench/workbench.web.main.js)
```
I have tried in both Chrome and Firefox. The same error occurs.
I have tried removing Stackblitz from my Github apps and re-adding it. I have rebooted my computer, signed out of stackblitz and back in, all to no avail.

It appears to be the Codeflow editor having the problem. If I go to the same public github repo in the classic view https://stackblitz.com/github/cjkirk09/js-lgzfka2, it loads just fine

### steps to reproduce

1. Go to https://stackblitz.com/~/github.com/cjkirk09/js-lgzfka2
2. See that it doesn't clone the repo properly and therefore never boots the web container
3. Go to https://stackblitz.com/github/cjkirk09/js-lgzfka2
4. See that it loads the project just fine

**Comment by Nemikolh** [comment]
Hi @cjkirk09 ! 

We had indeed an issue with our git integration. We deployed a fix and the issue should now be resolved.
