### ISSUE TITLE
Failed to load static HTML, CSS, JS template as standalone page

### ISSUE THREAD

**Issue by jack-vo** [stackblitz/core#2930]
Hi team,

When I tested the `Pure HTML / CSS / JS` template, I noticed that even though the page loaded just fine within StackBlitz development environment, when we load the project URL in standalone browser tab (by clicking Open in new tab or by copying/pasting the URL), the project will not load.

In the console, there would be an error `Preset not specified in configuration`. 
```
Uncaught (in promise) Error: Preset not sepcified in configuration
    at rt.<anonymous> (webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:8:207891)
    at Generator.next (<anonymous>)
    at webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:8:205947
    at new Promise (<anonymous>)
    at Z (webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:8:205684)
    at rt.config (webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:8:206973)
    at he.config (webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:8:232555)
    at Oe (preview-70b26ed60029a.js:2:582682)
    at Object.PREVIEW_INSTANTIATE_BUNDLE (preview-70b26ed60029a.js:2:583532)
    at preview-70b26ed60029a.js:2:563264
```

**Steps to replicate**
- Fork the `Pure HTML/CSS/JS` template or this Stackblitz repo https://stackblitz.com/edit/web-platform-nqbgpn?file=index.html
- Click `Open in new tab` to open the project URL in a new tab
- The loading spinner will keep spinning forever and there will be an error logged in the console

Thank you

**Comment by teociaps** [comment]
This problem appears to be a duplicate of issue #2828
