### ISSUE TITLE
Error: nodeUtil is not defined

### ISSUE THREAD

**Issue by himself65** [stackblitz/core#2940]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).

util module should be considered as a node internal package

```shell
Error: nodeUtil is not defined
    at <anonymous> (/home/projects/llqiawwrr.github/node_modules/pdf2json/lib/pdf.js)
    at eval (/home/projects/llqiawwrr.github/node_modules/pdf2json/lib/pdf.js:87:1)
    at _0x345efc._evaluate (https://llqiawwrrgithub-0ckm.w-credentialless.staticblitz.com/blitz.6854296d.js:352:378687)
    at async _0x345efc._evaluate (https://llqiawwrrgithub-0ckm.w-credentialless.staticblitz.com/blitz.6854296d.js:352:378298)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:2372)
```

### **Steps to Reproduce**

1. Go to https://stackblitz.com/github/run-llama/LlamaIndexTS/tree/main/examples?file=README.md
2.

```shell
ts-node ./readers/load-pdf.ts
```

### **Expected Behavior**

Parse pdf successfully

### **Screenshots/Screencast**

<img width="692" alt="image" src="https://github.com/stackblitz/core/assets/14026360/463d5d90-da80-473c-becb-ec47ff66065f">

**Additional Context/Questions**
Add any other context or questions regarding this bug.

```js
import nodeUtil from 'util';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

import { EventEmitter } from 'events';
import { Blob } from 'buffer';
import { DOMParser } from '@xmldom/xmldom';
// ...
```

**Comment by Nemikolh** [comment]
Hey @himself65! :wave: 

Oh this is surprising, because you can import `util` just fine in simpler examples (see: https://stackblitz.com/edit/node-xbjqyt)

So I think there's probably something else going on here. Also, I cannot reproduce your error, instead I get this:

![image](https://github.com/stackblitz/core/assets/4008156/068f5f8c-1ac0-4ef7-b53b-6361f6dd36cf)

Looking at `llamaindex`, it does not indeed export a `readers` module:

```
  "exports": {
    ".": {
      "types": "./index.d.mts",
      "import": "./index.mjs",
      "edge-light": "./index.edge-light.mjs",
      "require": "./index.js"
    },
    "./env": {
      "types": "./env.d.mts",
      "import": "./env.mjs",
      "edge-light": "./env.edge-light.mjs",
      "require": "./env.js"
    }
  },
```
