### ISSUE TITLE
Routing is not working

### ISSUE THREAD

**Issue by SreeDivyaReddy** [stackblitz/core#2981]
ERROR
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'react/'
Error: Cannot match any routes. URL Segment: 'react/'
at ApplyRedirects.noMatchError (https://angular-live-compiler-mghqut.stackblitz.io/turbo_modules/@angular/router@11.0.8/__ivy_ngcc__/bundles/router.umd.js:3069:20)
at CatchSubscriber.eval [as selector] (https://angular-live-compiler-mghqut.stackblitz.io/turbo_modules/@angular/router@11.0.8/__ivy_ngcc__/bundles/router.umd.js:3050:33)
at CatchSubscriber.error (https://angular-live-compiler-mghqut.stackblitz.io/turbo_modules/rxjs@6.6.3/internal/operators/catchError.js:46:31)
at Subscriber._error (https://angular-live-compiler-mghqut.stackblitz.io/turbo_modules/rxjs@6.6.3/internal/Subscriber.js:92:26)
at Subscriber.error (https://angular-live-compiler-mghqut.stackblitz.io/turbo_modules/rxjs@6.6.3/internal/Subscriber.js:72:18)
at Subscriber._error (https://angular-live-compiler-mghqut.stackblitz.io/turbo_modules/rxjs@6.6.3/internal/Subscriber.js:92:26)
at Subscriber.error (https://angular-live-compiler-mghqut.stackblitz.io/turbo_modules/rxjs@6.6.3/internal/Subscriber.js:72:18)
at Subscriber._error (https://angular-live-compiler-mghqut.stackblitz.io/turbo_modules/rxjs@6.6.3/internal/Subscriber.js:92:26)
at Subscriber.error (https://angular-live-compiler-mghqut.stackblitz.io/turbo_modules/rxjs@6.6.3/internal/Subscriber.js:72:18)
at Subscriber._error (https://angular-live-compiler-mghqut.stackblitz.io/turbo_modules/rxjs@6.6.3/internal/Subscriber.js:92:26)
Made 7

**Comment by SreeDivyaReddy** [comment]
const routes: Routes = [
  { path: 'react', component: ApplicationComponent },
  { path: 'template', component: TemplateApplication },
];
app.component.html
<button (click)="navigate()">Home</button>

app.component.ts

constructor(private router: Router) {}
  navigate() {
    this.router.navigate(['react', '']);
  }
