### ISSUE TITLE
[Nuxt] starter project throws ECONNREFUSED 

### ISSUE THREAD

**Issue by bogdan0083** [stackblitz/core#3011]
### **Description of Bug**
Hey guys! I can't run Nuxt starter project. It throws the following errors:
```
ℹ Vite server warmed up in 794ms                                                 11:45:59
✔ Nuxt Nitro server built in 727 ms                                        nitro 11:45:59
ℹ Vite client warmed up in 2622ms                                                11:46:00

 ERROR  [nuxt] [request error] [unhandled] [500] Context is not available
  at use (./node_modules/unctx/dist/index.mjs:50:15)  
  at _IfgmapON6h/< (./.nuxt/dev/index.mjs:642:174)  
  at serialTaskCaller/</</< (./node_modules/hookable/dist/index.mjs:68:78)  
  at run (./node_modules/hookable/dist/index.mjs:61:43)  
  at serialTaskCaller/</< (./node_modules/hookable/dist/index.mjs:68:56)


 ERROR  [h3] [unhandled] connect ECONNREFUSED 127.0.0.1:54654                    11:46:01

  at ke< (https://nuxtstarterwzsxae-xkc5.w-corp-staticblitz.com/blitz.810981ba.js:36:7078)
  at afterConnect (https://nuxtstarterwzsxae-xkc5.w-corp-staticblitz.com/blitz.810981ba.js:55:18524)
  at  (https://nuxtstarterwzsxae-xkc5.w-corp-staticblitz.com/blitz.810981ba.js:371:14070)
  at _0x398360 (https://nuxtstarterwzsxae-xkc5.w-corp-staticblitz.com/blitz.810981ba.js:352:154315)
  at _0x4b242d/< (https://nuxtstarterwzsxae-xkc5.w-corp-staticblitz.com/blitz.810981ba.js:352:154055)

```

### **Steps to Reproduce**

1. Go to [https://stackblitz.com/](https://stackblitz.com/)
2. Click on 'New Project'
3. Choose *Nuxt.js* template (available in Popular tab)
4. Wait for project to initialize (it runs `npm install && npm run dev`)
5. The project throws 500 ECONNREFUSED error

### **Expected Behavior**
It should display `NuxtWelcome` screen and not to throw any errors.

### **Screenshots/Screencast**
<img width="1111" alt="screenshot" src="https://github.com/stackblitz/core/assets/7077307/e5eebd62-8278-426e-a60b-0a34556b3194">

**Additional Context/Questions**
Here's public URL to the project that doesn't work: https://stackblitz.com/edit/nuxt-starter-wzsxae?file=README.md

**Comment by Nemikolh** [comment]
Not sure why this got closed but I wanted to let you know that this is fixed in more recent version of Nuxt.

See https://stackblitz.com/edit/nuxt-starter-4yexk6 (where I only updated the version of Nuxt).
