### ISSUE TITLE
ReadableStream not supports AsyncIterator

### ISSUE THREAD

**Issue by himself65** [stackblitz/core#3041]
### **Description of Bug**

```js
const r = new ReadableStream({
  start: (controller) => {
    controller.enqueue('1');
    controller.enqueue('2');
    controller.enqueue('3');
    controller.close();
  },
});

for await (const v of r) {
  console.log('v', v);
}
```

```sh
node ./index.js
SyntaxError: Unexpected reserved word
    at __global_eval__ (https://node5guajt-1lt4.w-credentialless-staticblitz.com/blitz.0314a412.js:1:263)
    at _0x508ec2 (https://node5guajt-1lt4.w-credentialless-staticblitz.com/blitz.0314a412.js:352:199586)
    at _0x4e27ea._compile (https://node5guajt-1lt4.w-credentialless-staticblitz.com/blitz.0314a412.js:352:197534)
    at _0x4ee9b2.instantiate (https://node5guajt-1lt4.w-credentialless-staticblitz.com/blitz.0314a412.js:352:376808)
    at _0x555b21._instantiate (https://node5guajt-1lt4.w-credentialless-staticblitz.com/blitz.0314a412.js:352:381436)
    at _0x555b21.instantiate (https://node5guajt-1lt4.w-credentialless-staticblitz.com/blitz.0314a412.js:352:379740)
    at ModuleJob._instantiate (https://node5guajt-1lt4.w-credentialless-staticblitz.com/blitz.0314a412.js:181:1509)
    at async ModuleJob.run (https://node5guajt-1lt4.w-credentialless-staticblitz.com/blitz.0314a412.js:181:2327)
```

### **Steps to Reproduce**

1. Go to https://stackblitz.com/edit/node-5guajt?file=index.js
2. node index.js

### **Screenshots/Screencast**

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by Nemikolh** [comment]
Hey @himself65! Thanks for the report! This is indeed a bug.

I'll add it to our internal tracker and keep you updated 👍
