### ISSUE TITLE
Vite project not running

### ISSUE THREAD

**Issue by NoelDeMartin** [stackblitz/core#3142]
### **Description of Bug**

I wanted to give Stackblitz a try with a new project I created, which is using Vite and as far as I can tell it's pretty standard. However, when I launched the repository I got a cryptic error and I'm not sure what's broken.

### **Steps to Reproduce**

1. Go to https://stackblitz.com/github/noeldemartin/vivant
2. Wait for the `npm install && npm run dev` command to complete
3. See error

### **Expected Behavior**

The dev command should succeed and open the app.

### **Screenshots/Screencast**

This is the complete log I get:

```
❯ npm install && npm run dev
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm WARN deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

added 741 packages in 15s

171 packages are looking for funding
  run `npm fund` for details

> dev
> npm run dev -ws --if-present


> dev
> vite

failed to load config from /home/projects/nbwiymboxb.github/playground/vite.config.ts
error when starting dev server:
_0x5d80aa@https://nbwiymboxbgithub-biz4.w-corp-staticblitz.com/blitz.34c588ed.js:40:68089
_0x365794@https://nbwiymboxbgithub-biz4.w-corp-staticblitz.com/blitz.34c588ed.js:40:896463
internal/modules/cjs/loader/Module._extensions[".node"]@https://nbwiymboxbgithub-biz4.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:15217
internal/modules/cjs/loader/Module.prototype.load@https://nbwiymboxbgithub-biz4.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:12820
internal/modules/cjs/loader/Module._load@https://nbwiymboxbgithub-biz4.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:10273
internal/modules/cjs/loader/Module.prototype.require@https://nbwiymboxbgithub-biz4.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:13097
require3@https://nbwiymboxbgithub-biz4.w-corp-staticblitz.com/builtins.ddb8d84d.js:163:2815
_0x5bfa83@https://nbwiymboxbgithub-biz4.w-corp-staticblitz.com/blitz.34c588ed.js:40:792044
@file:///home/projects/nbwiymboxb.github/node_modules/@tailwindcss/oxide/index.js#cjs:177:31
_0x34b746@https://nbwiymboxbgithub-biz4.w-corp-staticblitz.com/blitz.34c588ed.js:40:792679
internal/modules/cjs/loader/Module.prototype._compile@https://nbwiymboxbgithub-biz4.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:14246
internal/modules/cjs/loader/Module._extensions[".js"]@https://nbwiymboxbgithub-biz4.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:14855
internal/modules/cjs/loader/Module.prototype.load@https://nbwiymboxbgithub-biz4.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:12820
internal/modules/cjs/loader/Module._load@https://nbwiymboxbgithub-biz4.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:10273
internal/modules/esm/translators/commonjsStrategy/<@https://nbwiymboxbgithub-biz4.w-corp-staticblitz.com/builtins.ddb8d84d.js:160:3630
_evaluate@https://nbwiymboxbgithub-biz4.w-corp-staticblitz.com/blitz.34c588ed.js:40:784934
_evaluate@https://nbwiymboxbgithub-biz4.w-corp-staticblitz.com/blitz.34c588ed.js:40:785078

npm ERR! Lifecycle script `dev` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: undefined 
npm ERR!   at location: /home/projects/nbwiymboxb.github/playground 
```

**Additional Context/Questions**

I am using node 22 in my machine, but I tried using node 18 as well and it seems to work fine, so I don't think the node version is the problem.

**Comment by NoelDeMartin** [comment]
I just tried in Chrome (I was using Firefox), and this time I get a better error:

```
failed to load config from /home/projects/nbwiymboxb.github/playground/vite.config.ts
error when starting dev server:
Error: Cannot load native addon because loading addons is disabled: /home/projects/nbwiymboxb.github/node_modules/@tailwindcss/oxide-linux-x64-musl/tailwindcss-oxide.linux-x64-musl.node
    at _0x2e7c4c._0x365794 [as dlopen] (https://nbwiymboxbgithub-biz4.w-credentialless-staticblitz.com/blitz.34c588ed.js:40:896463)
    at Module._extensions..node (https://nbwiymboxbgithub-biz4.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:144:15217)
    at Module.load (https://nbwiymboxbgithub-biz4.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:144:12820)
    at Module._load (https://nbwiymboxbgithub-biz4.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:144:10273)
    at Module.require (https://nbwiymboxbgithub-biz4.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:144:13097)
    at require3 (https://nbwiymboxbgithub-biz4.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:163:2815)
    at _0x5bfa83 (https://nbwiymboxbgithub-biz4.w-credentialless-staticblitz.com/blitz.34c588ed.js:40:792044)
    at Object.eval (file:///home/projects/nbwiymboxb.github/node_modules/@tailwindcss/oxide/index.js#cjs:177:31)
    at Object._0x34b746 (https://nbwiymboxbgithub-biz4.w-credentialless-staticblitz.com/blitz.34c588ed.js:40:792686)
    at Module._compile (https://nbwiymboxbgithub-biz4.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:144:14246)
npm ERR! Lifecycle script `dev` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: undefined 
npm ERR!   at location: /home/projects/nbwiymboxb.github/playground 
```

It seems like this happens because I'm using Tailwind v4, so I guess this is a duplicate of #1855? I'm leaving it open since the error is not the same in Firefox, but if you think it's the same feel free to close as duplicated. Or maybe consider it a bug that I didn't get the correct error log in Firefox :).
