### ISSUE TITLE
404 Page when I click open in Stack Blitz from my Bolt.Al project.

### ISSUE THREAD

**Issue by benjpalitz** [stackblitz/core#3216]
### **Description of Bug**
My bolt ai project is no longer listening / showing changes / showing fixes I'm asking it to make. I read the documentation that stated creating a fork could help. When I click open in Stack Blitz at the top right, in my Bolt AI project, it directs me to a 404 screen.

### **Steps to Reproduce**

1. Go to 'Bolt AI project (potentially one that's large to mimic my project)'
2. Click on 'open in Stack Blitz'
3. See "404: Not Found Sorry, we couldn’t find the page you’re looking for.

The page may have been moved or deleted, please check the URL and try again."

### **Expected Behavior**
Taken to the stack blitz project properly to fork the code, so the Bolt AI project will work correctly again my requirement inputs.

### **Screenshots/Screencast**
<img width="692" alt="Screenshot 2024-12-26 at 9 16 34 PM" src="https://github.com/user-attachments/assets/4eb51fda-db58-4984-9e7a-f7334a67fecc" />

https://github.com/user-attachments/assets/85995e46-d866-4d78-b022-f89d818a2b2c

**Additional Context/Questions**
Not Currently.

**Comment by a080865** [comment]
`NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Zj (https://bolt.new/assets/components-BPQqK2_k.js:24:26518)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27829)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
Component stack: 
    at div
    at div
    at MenuContent$1 (https://bolt.new/assets/_index-D9ZkhskI.js:88:127145)
    at div
    at div
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at https://bolt.new/assets/_index-D9ZkhskI.js:88:123725
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-D7uIdHAn.js:1:1119)
    at div
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at https://bolt.new/assets/_index-D9ZkhskI.js:145:9492
    at https://bolt.new/assets/_index-D9ZkhskI.js:145:26364
    at Chat (https://bolt.new/assets/_index-D9ZkhskI.js:145:25146)
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-D7uIdHAn.js:1:1119)
    at div
    at IndexLayout (https://bolt.new/assets/_index-D9ZkhskI.js:145:39817)
    at Index$1
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-D7uIdHAn.js:1:1119)
    at Layout (https://bolt.new/assets/root-CWXDg_kQ.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)`

**Comment by a080865** [comment]
![Screenshot_20241231_133400](https://github.com/user-attachments/assets/629a8103-8a1e-44a7-a77b-e6856713bf3e)
