### ISSUE TITLE
IE 11 and Sass results in "Out of stack space" error

### ISSUE THREAD

**Issue by tiliev** [stackblitz/core#476]
### Desription
Opening a StackBlitz sample with Sass styles in IE 11 results in a console error and does not load.

### Demo
https://stackblitz.com/edit/ie-11-sass-issue

More complex demo - https://stackblitz.com/edit/ie-11-sass-console-error

### Screenshots

![sb-ie11-error](https://user-images.githubusercontent.com/6439482/39811564-bdb44ae2-5391-11e8-9474-1c0c2682370f.PNG)

![sb-ie11-error-2](https://user-images.githubusercontent.com/6439482/39811569-c068bd4a-5391-11e8-9984-e864df419ade.PNG)

### Error Stacktrace
"Error: Out of stack space\n   at Y_ (https://cdnjs.cloudflare.com/ajax/libs/sass.js/0.10.6/sass.sync.min.js:1:1252842)\n   
at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/sass.js/0.10.6/sass.sync.min.js:1:2251107)\n   
at Y_ (https://cdnjs.cloudflare.com/ajax/libs/sass.js/0.10.6/sass.sync.min.js:1:1260508)\n   
at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/sass.js/0.10.6/sass.sync.min.js:1:1489943)\n   
at dynCall_iiiiiiii (https://cdnjs.cloudflare.com/ajax/libs/sass.js/0.10.6/sass.sync.min.js:1:3375026)\n   
at invoke_iiiiiiii (https://cdnjs.cloudflare.com/ajax/libs/sass.js/0.10.6/sass.sync.min.js:1:28008)\n   
at Y_ (https://cdnjs.cloudflare.com/ajax/libs/sass.js/0.10.6/sass.sync.min.js:1:1270973)\n   
at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/sass.js/0.10.6/sass.sync.min.js:1:2108090)\n   
at dynCall_iiiiii (https://cdnjs.cloudflare.com/ajax/libs/sass.js/0.10.6/sass.sync.min.js:1:3375756)\n   
at invoke_iiiiii (https://cdnjs.cloudflare.com/ajax/libs/sass.js/0.10.6/sass.sync.min.js:1:29273)"

### IE 11 version

![ie-11-version](https://user-images.githubusercontent.com/6439482/39812160-3ded8ef6-5394-11e8-940e-20e3c3c11fd8.PNG)

P.S. The bug does not reproduce always.

**Comment by EricSimons** [comment]
It looks like Sass' compiler is using up too much memory in IE specifically for these projects 🤔

Tbh I'm not sure if this is something we can fix, as it would likely require us to rewrite the Sass compiler itself. Fwiw we've never seen this error in evergreen browsers (edge, ffx, chrome) which are our primary compat targets.

**Comment by tiliev** [comment]
Eventually we decided to use CSS when opening our samples in IE 11 and SASS for any other browser.
