### ISSUE TITLE
Ionic Export dependency error

### ISSUE THREAD

**Issue by rmallermartins** [stackblitz/core#639]
I created an Ionic project, exported it and ran `npm install`.

When I tried running `ionic serve`, got the following error:

```
[WARN] Detected locally installed Ionic CLI, but it's too old--using global CLI.
> ionic-app-scripts serve --address 0.0.0.0 --port 8100 --livereload-port 35729 --dev-logger-port 53703 --nobrowser
[app-scripts] module.js:491
[app-scripts]     throw err;
[app-scripts]     ^
[app-scripts]
[app-scripts] Error: Cannot find module '@angular/tsc-wrapped/src/tsc'
[app-scripts]     at Function.Module._resolveFilename (module.js:489:15)
[app-scripts]     at Function.Module._load (module.js:439:25)
[app-scripts]     at Module.require (module.js:517:17)
[app-scripts]     at require (internal/module.js:11:18)
[app-scripts]     at Object.<anonymous> (C:\Users\Rodrigo\Desktop\magma1-stack\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:7:13)
[app-scripts]     at Module._compile (module.js:573:30)
[app-scripts]     at Object.Module._extensions..js (module.js:584:10)
[app-scripts]     at Module.load (module.js:507:32)
[app-scripts]     at tryModuleLoad (module.js:470:12)
[app-scripts]     at Function.Module._load (module.js:462:3)

[ERROR] @ionic/app-scripts is required for ionic serve to work properly.

        Looks like @ionic/app-scripts isn't installed in this project.

        This package is required for ionic serve in ionic/angular 4 projects.
```

It's fixed if I manually install @angular/tsc-wrapped package.

Is this a bug, or am I doing something wrong?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
